{{#if deployment.enabled}}
{{#if deployment.type "===" "chart"}}
chart-dirs:
  - {{deployment.chart.root}}
{{#if deployment.chart.additionalRepos}}
chart-repos:
  {{#each deployment.chart.additionalRepos}}
  - {{this.name}}={{this.url}}
  {{/each}}
{{/if}}
check-version-increment: false
debug: true
remote: origin
validate-chart-schema: true
validate-maintainers: false
validate-yaml: true
target-branch: {{git.main_branch}}
{{/if}}
{{/if}}